apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flaskoperators.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: FlaskOperator
    plural: flaskoperators
    singular: flaskoperator
    shortNames:
      - fos
      - fo
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true